<h1><?php echo $this->escapeHtml('My books'); ?></h1>
<p>
    <a class="btn btn-primary" href="<?php echo $this->url('books', array('controller'=>'index','action'=>'add'));?>">Add book</a>
</p>

<table class="table">
<tr>
    <th>
        <a href="<?php echo $this->url('books',
            array('action'=>'list', 'id' => 'title'));?>"> 
            Title
        </a>
    </th>
    <th>
        <a href="<?php echo $this->url('books',
            array('action'=>'list', 'id' => 'description'));?>"> 
            Description
        </a>
    </th>
    <th>
        <a href="<?php echo $this->url('books',
            array('action'=>'list', 'id' => 'author'));?>">
            Author
        </a>
    </th>
    <th></th>
</tr>
<?php foreach ($books as $book) : ?>
<tr>
    <td><?php echo $this->escapeHtml($book->title);?></td>
    <td><?php echo $this->escapeHtml($book->description);?></td>
    <td><?php echo $this->escapeHtml($book->author);?></td>
    <td>
        <a class="btn btn-primary" href="<?php echo $this->url('books',
            array('action'=>'edit', 'id' => $book->id));?>">Edit</a>

        <a class="btn btn-danger" href="<?php echo $this->url('books',
            array('action'=>'delete', 'id' => $book->id));?>">Delete</a>

    </td>
</tr>
<?php endforeach; ?>
</table>